#!/usr/bin/env bash

set -ue

DEFAULT_GROUPS='wheel,adm,cdrom'
DEFAULT_UID='1000'

echo 'Please create a default UNIX user account. The username does not need to match your Windows username.'
echo 'For more information visit: https://aka.ms/wslusers'

if getent passwd "$DEFAULT_UID" > /dev/null ; then
  echo 'User account already exists, skipping creation'
  exit 0
fi

while read -r -p 'Enter new UNIX username: ' username; do
  # Create the user
  if useradd "$username" -u "$DEFAULT_UID" -G "$DEFAULT_GROUPS" && passwd "$username"; then
    break
  else
    userdel -r "$username"
  fi
done
